2022-12-08 16:31:08,280 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\e908cefa9bac6212_chromedriver.exe
2022-12-08 16:31:11,627 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2022-12-08 16:31:21,918 - [INFO] - main_ERKNM - autorize(138) - Autorization successfull completed!
2022-12-08 16:56:29,654 - [INFO] - direct_sql.py - multiple_inserts(135) - старт программы
2022-12-08 17:39:36,816 - [INFO] - direct_sql.py - multiple_inserts(144) - Все проверки успешно занесены!
2022-12-08 19:24:27,380 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\6c53a1dffc2fa388_chromedriver.exe
2022-12-08 19:24:30,426 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2022-12-08 19:26:17,829 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\93a98717d92e3871_chromedriver.exe
2022-12-08 19:26:20,972 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2022-12-08 19:29:48,579 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\acf826722508180d_chromedriver.exe
2022-12-08 19:29:51,158 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2022-12-08 19:30:01,269 - [INFO] - main_ERKNM - autorize(138) - Autorization successfull completed!
2022-12-08 19:40:18,964 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\f13fe66b0a12da59_chromedriver.exe
2022-12-08 19:40:21,604 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2022-12-08 19:40:31,471 - [INFO] - main_ERKNM - autorize(138) - Autorization successfull completed!
2022-12-08 19:44:08,244 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\95da297ceab6e08e_chromedriver.exe
2022-12-08 19:44:11,127 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2022-12-08 19:44:22,917 - [INFO] - main_ERKNM - autorize(138) - Autorization successfull completed!
2022-12-08 19:44:26,673 - [INFO] - exp.py - database_inserts_conductor(110) - началась запись в базу данных...
2022-12-08 19:44:26,713 - [INFO] - exp.py - database_inserts_conductor(131) - Все проверки успешно занесены!
2022-12-08 19:44:29,770 - [INFO] - exp.py - database_inserts_conductor(110) - началась запись в базу данных...
2022-12-08 19:44:29,806 - [INFO] - exp.py - database_inserts_conductor(131) - Все проверки успешно занесены!
2022-12-08 20:50:26,400 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\6632f5b38a933873_chromedriver.exe
2022-12-08 20:50:29,200 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2022-12-08 20:50:39,080 - [INFO] - main_ERKNM - autorize(138) - Autorization successfull completed!
2022-12-08 20:51:18,560 - [WARNING] - urllib3.connectionpool - urlopen(812) - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A60B61DAE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')': /session/d8cf649e3dc07aaa9854e81d7ec2dfeb
2022-12-08 20:51:22,633 - [WARNING] - urllib3.connectionpool - urlopen(812) - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A60B5D56F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')': /session/d8cf649e3dc07aaa9854e81d7ec2dfeb
2022-12-08 20:51:26,706 - [WARNING] - urllib3.connectionpool - urlopen(812) - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A60FA948B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')': /session/d8cf649e3dc07aaa9854e81d7ec2dfeb
